name: CoordReminder
main: de.slevermann.minecraft.coordreminder.CoordReminderPlugin
description: ${project.description}
version: ${project.version}
author: sonOfRa
commands:
  coord:
    description: Interact with stored coordinates
    usage: |
      Usage:
      /<command>: show current coordinates
      /<command> list: list saved coordinates
      /<command> set [name]: save current coordinates as [name]
      /<command> set [name] [x] [y] [z]: save coordinate x, y, z as [name]
      /<command> get [name]: get coordinates saved as [name]
      /<command> share [name]: share coordinates saved as [name] to chat
      /<command> delete [name]: delete coordinates saved as [name]
      /<command> clear: delete all saved coordinates
