name: CoordReminder
main: de.slevermann.minecraft.coordreminder.CoordReminderPlugin
description: Allows saving and recalling of coordinates
version: 1.3.0
author: sonOfRa
commands:
  coord:
    description: Interact with stored coordinates
    usage: |
      Usage:
      /<command>: show current coordinates
      /<command> list: list saved coordinates
      /<command> set [name]: save current coordinates as [name]
      /<command> get [name]: get coordinates saved as [name]
      /<command> delete [name]: delete coordinates saved as [name]
      /<command> clear: delete all saved coordinates
